version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jobsearch_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jobsearch
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: jobsearch_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobsearch"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: